# Generated by Django 6.0.6 on 2026-06-15 11:00



import datetime

from django.db import migrations, models





class Migration(migrations.Migration):



    dependencies = [

        ('cosx_home', '0003_alter_orders_order_date'),

    ]



    operations = [

        migrations.AlterField(

            model_name='orders',

            name='order_date',

            field=models.DateTimeField(default=datetime.datetime(2026, 6, 15, 11, 0, 42, 910701, tzinfo=datetime.timezone.utc)),

        ),

    ]


